CREATE TABLE users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    TEXT,
    username TEXT,
    password TEXT,
    role     VARCHAR(20),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

